### ISSUE TITLE
Fix alignment in System Health Check

### ISSUE THREAD

**Issue by arobillard** [Ingenium-Applied-Project/companion_app#42]
In the system health check everything is nicely aligned left except for "Low" in the last row. You should fix it for consistency

![Screen Shot 2024-04-07 at 10 07 13 AM](https://github.com/Ingenium-Applied-Project/companion_app/assets/22084666/60b278b3-3a99-4d1d-a910-60502d03da7d)
![Screen Shot 2024-04-07 at 10 08 22 AM](https://github.com/Ingenium-Applied-Project/companion_app/assets/22084666/545883e1-bd77-4204-a7b6-879cd4e55549)

**Comment by sous0049** [comment]
Hi Adam (@arobillard), fixed as requested and pushed to the main branch, here is a screenshot of the fix, due to Vercel limitations on the free tier.

<img width="709" alt="image" src="https://github.com/Ingenium-Applied-Project/companion_app/assets/113060914/73366766-78da-45c8-8e15-7ef5a74870de">

<img width="407" alt="image" src="https://github.com/Ingenium-Applied-Project/companion_app/assets/113060914/7823363a-2314-47af-9a3f-258f092f2e6f">
